language: node_js
cache:
  directories:
  - node_modules
before_install:
- npm install -g ionic
before_script: 
script:
- npm install
- ionic build --prod
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: www/
  on:
    branch: master